// Generated by ts-to-zod
import { z } from "zod";

export const settingsSchema = z.object({
  projects: z.array(z.string()),
  threshold: z
    .object({
      pullRequests: z.number().optional(),
      issues: z.number().optional(),
      vulnerabilityAlerts: z.number().optional(),
    })
    .optional(),
});

const stargazerSchema = z.object({
  id: z.string(),
  name: z.string().nullable(),
  avatarUrl: z.string(),
});

export const projectSchema = z.object({
  id: z.string(),
  url: z.string(),
  name: z.string(),
  pullRequests: z.object({
    totalCount: z.number(),
  }),
  vulnerabilityAlerts: z.object({
    totalCount: z.number(),
  }),
  issues: z.object({
    totalCount: z.number(),
  }),
  stargazers: z.object({
    totalCount: z.number(),
    nodes: z.array(stargazerSchema),
  }),
});
